contact_links:
  - name: ğŸ’¬ Contact support
    url: https://xdev.software/en/services/support
  - name: ğŸ±â€ğŸ’» Security vulnerability
    url: https://github.com/xdev-software/template-placeholder/security/advisories/new
