contact_links:
  - name: ğŸ’¬ Contact support
    url: https://xdev.software/en/services/support
    about: "If you need support as soon as possible and you can't wait for any pull request, feel free to use our support"
  - name: ğŸ±â€ğŸ’» Security vulnerability
    url: https://github.com/AB-xdev/issue-template-test/security/advisories/new
    about: "Please report security vulnerabilities here"
